### PR TITLE
require recent rmagick without deprecation warning

### PR DESCRIPTION
**Pull request by bluta**
since rmagick 2.14, this commit of theirs:
https://github.com/gemhome/rmagick/commit/77827346b046c6e42ce27909970036d7cc1f16de

### CODE REVIEW

**Comment by bluta** [comment]
hi @toretore, is there anything else I can help with to get this merged?

**Comment by doredesign** [comment]
+1

**Comment by soniaconnolly** [comment]
+1

**Comment by kwent** [comment]
+1. Please merge and release version !

**Comment by zeppelin** [comment]
@toretore ping

**Comment by toretore** [comment]
ace7a8c

**Pull request closed without merging**
